### PR TITLE
Set the coverflow element and Fix stability

### PR DESCRIPTION
**Pull request by DohyungLim**
- Set the default value to the coverflow element.
- Remove 'Widget Option' Attribute.
- External images apply to coverflow.
- After Images select, effect and size select as possible.

Signed-off-by: DoHyung Lim <delight.lim@samsung.com>

### CODE REVIEW

**Comment by DohyungLim** [comment]
@TomaszLukawskiSam 
It's very strange.
I checked the implementation in VSC-Design-Editor.
The attached image does not break as shown.
I copied the code implemented in VSC-Design-Editor to TAU-Design-Editor equally.
Does updating to TAU-Design-Editor apply to VSC-Design-Editor?

Wouldn't the issue occur somewhere else? please check.

**Comment by DohyungLim** [comment]
@korneliakobiela 
Tomasz says that the Attributes Tab breaks.
I and Ms.Hwang (Cookie) confirmed on the local PC that the issue was resolved.

can you please this issue reproduce on your PC?
If you have same attributes tab break, can you guide my PR problem?

**Comment by DohyungLim** [comment]
@TomaszLukawskiSam 
Sorry. There is a modification in my code to eliminate Lint errors.
The problem arises here. I updated the code with changes.
Please check it last.

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam
> Sorry. There is a modification in my code to eliminate Lint errors.
> The problem arises here. I updated the code with changes.
> Please check it last.
@DohyungLim 
The attributes look good :)

**Comment by DohyungLim** [comment]
@TomaszLukawskiSam @korneliakobiela 
please merge to this PR.

**Pull request merged**
