### PR TITLE
Load styles restricted by media queries in DE

### PR DESCRIPTION
**Pull request by hsiwkin**
[Problem] No fish-eye effect in DE Live Preview
[Solution] I've removed "virtually" media queries for round devices

Signed-off-by: Hubert Siwkin <h.siwkin@samsung.com>

### CODE REVIEW

**Comment by hsiwkin** [comment]
To view changes in this PR I recommend selecting on option to "Hide whitespace changes" as I've added quite a lot of them which can dimnish the "real" changes.
gitHuboption

**Comment by lslachciak** [comment]
This is very hard to differentiate which are eslint related changes and which refer to patch only :(
We should consider not fixing eslint issues in the same patch because it is confusing (spaces to tabs?)

**Comment by lslachciak** [comment]
Sorry @hsiwkin I missed your last comment. hide white-spaces option works perfectly

**Comment by hsiwkin** [comment]
:+1:

**Pull request merged**
